[package]
name = "nomino"
version = "0.1.2"
authors = ["Navid <yaa110@gmail.com>"]
description = "Batch rename utility for developers"
edition = "2018"
repository = "https://github.com/yaa110/nomino"
license = "MIT OR Apache-2.0"

[dependencies]
atty = "0.2"
clap = { version = "2.33", features = ["yaml"] }
colored = "1.9"
prettytable-rs = "0.8"
regex = "1.3"
serde_json = "1.0"

[profile.release]
debug = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
